<a href="https://colab.research.google.com/github/Anuoluwapo003/Assignment-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [ ]:
#1 dimension
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
#2 dimension
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.shape
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#3 dimension
arr3 = np.array([[[[1, 2, 3], [4, 5, 7]], [[3, 4, 5], [0, 0, 0]],[[5, 7, 8], [8, 9, 4]]]])
print(arr3)

[[[[1 2 3]
   [4 5 7]]

  [[3 4 5]
   [0 0 0]]

  [[5 7 8]
   [8 9 4]]]]


In [ ]:
arr4 = np.zeros(4)
arr4

array([0., 0., 0., 0.])

In [ ]:
arr5=np.ones(8)
arr5

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr6=np.arange(10,20,2)
arr6

array([10, 12, 14, 16, 18])

In [ ]:
arr7=np.linspace(1,15, num=4)
arr7

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [ ]:
np.sort(arr2)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr2[1:]

array([[4, 5, 6]])

In [ ]:
arr2.shape

(2, 3)